# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/hskas/Documents/EE108/Lab1/Lab1.runs/synth_1/lab1_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/hskas/Documents/EE108/Lab1/Lab1.cache/wt [current_project]
set_property parent.project_path C:/Users/hskas/Documents/EE108/Lab1/Lab1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/hskas/AppData/Roaming/Xilinx/Vivado/2025.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/hskas/Downloads/lab1-main/lab1-main/hdmi_tx_ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/hskas/Documents/EE108/Lab1/Lab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/arbiter.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/brute_force_synchronizer.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/button_press_unit.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/cam.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/debouncer.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/encoder.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/ff_lib.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/hash_rom.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/hash_round.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/hasher.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/dvi_defines.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/input_box.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/lab1_interface.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/length_finder.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/one_pulse.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/rotator.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/tcgrom.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/verifier.v
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/lab1_top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/video_package_800x480.vhd
  C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/imports/lab1starterfiles/vga_controller_800x480_60.vhd
}
read_ip -quiet C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/Users/hskas/Documents/EE108/Lab1/Lab1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/hskas/Documents/EE108/Lab1/Lab1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hskas/Documents/EE108/Lab1/Lab1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hskas/Documents/EE108/Lab1/Lab1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hskas/Downloads/lab1_starter_files/lab1starterfiles/lab1.xdc
set_property used_in_implementation false [get_files C:/Users/hskas/Downloads/lab1_starter_files/lab1starterfiles/lab1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top lab1_top -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab1_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file lab1_top_utilization_synth.rpt -pb lab1_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
